# Generated by Django 5.0 on 2023-12-20 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationTokens',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=255)),
                ('expired_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('last_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WiFiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=255)),
                ('bssid', models.CharField(max_length=17)),
                ('rssi', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_type', models.IntegerField(default=0)),
            ],
        ),
    ]
