# Generated by Django 5.0 on 2023-12-20 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifidata',
            name='id',
            field = models.JSONField(default=uuid.uuid4, primary_key=False),
        ),
        migrations.AddField(
            model_name='wifidata',
            name='wifi_data_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
