# Generated by Django 5.0 on 2023-12-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_wifidata_id_wifidata_wifi_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifidata',
            old_name='latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='wifidata',
            old_name='longitude',
            new_name='y',
        ),
    ]
