# Generated by Django 4.1 on 2024-04-15 10:00

from django.db import migrations, models

def set_default_data_type(apps, schema_editor):
    WiFiData = apps.get_model('api', 'WiFiData')
    WiFiData.objects.filter(data_type__isnull=True).update(data_type=1)

class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_latitude_wifidata_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wifidata",
            name="data_type",
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(set_default_data_type),
    ]
